import { ProductInput } from "@/lib/models";

export const seedProducts: ProductInput[] = [
  {
    title: "Logitech G Pro X Wireless Gaming Headset",
    description:
      "Clear voice comms, low-latency wireless, and long-wear comfort for ranked sessions.",
    category: "Gaming",
    image: "/images/products/Logitech-headset.jpg",
    price: 199,
    compareAtPrice: 229,
    stock: 30,
    supplierName: "Logi Global Supply",
    supplierUrl: "https://supplier.example.com/logitech-g-pro-x",
    featured: true,
    active: true,
  },
  {
    title: "Anker PowerCore 20000mAh Power Bank",
    description:
      "Reliable high-capacity backup battery for phones, tablets, and mobile workstation setups.",
    category: "Accessories",
    image: "/images/products/AnkerPowerBank.jpg",
    price: 59,
    compareAtPrice: 69,
    stock: 80,
    supplierName: "Anker Wholesale",
    supplierUrl: "https://supplier.example.com/anker-powercore-20000",
    featured: true,
    active: true,
  },
  {
    title: "KWG Orion E1 RGB Gaming Mouse",
    description:
      "Ergonomic wired gaming mouse with fast tracking and programmable buttons.",
    category: "Peripherals",
    image: "/images/products/gaming-mouse1.jpg",
    price: 26,
    compareAtPrice: 29,
    stock: 120,
    supplierName: "Orbit Tech Supply",
    supplierUrl: "https://supplier.example.com/kwg-orion-e1",
    featured: true,
    active: true,
  },
  {
    title: "Dell XPS 13 Ultra Thin Laptop",
    description:
      "Premium lightweight laptop with fast SSD storage and all-day productivity battery life.",
    category: "Laptop",
    image: "/images/products/laptop.jpg",
    price: 1249.99,
    compareAtPrice: 1399.99,
    stock: 24,
    supplierName: "Latitude Devices",
    supplierUrl: "https://supplier.example.com/dell-xps-13",
    featured: true,
    active: true,
  },
  {
    title: "HP Spectre x360 Convertible Laptop",
    description:
      "Touch-enabled 2-in-1 laptop built for creators, students, and business use.",
    category: "Laptop",
    image: "/images/products/hplaptop.jpg",
    price: 1149,
    compareAtPrice: 1299,
    stock: 20,
    supplierName: "HP Distribution Hub",
    supplierUrl: "https://supplier.example.com/hp-spectre-x360",
    featured: false,
    active: true,
  },
  {
    title: "Acer Predator Orion 7000 Gaming Desktop",
    description:
      "High-performance gaming tower with modern cooling and upgrade-ready internals.",
    category: "Desktop",
    image: "/images/products/acerdesktop.jpg",
    price: 1799,
    compareAtPrice: 1999,
    stock: 10,
    supplierName: "Acer Commercial",
    supplierUrl: "https://supplier.example.com/acer-predator-orion-7000",
    featured: true,
    active: true,
  },
  {
    title: "Apple iMac 24-inch M3 Retina",
    description:
      "All-in-one desktop with retina display and efficient Apple silicon performance.",
    category: "Desktop",
    image: "/images/products/appledesktop.jpg",
    price: 1599,
    compareAtPrice: 1699,
    stock: 12,
    supplierName: "Apple Reseller Network",
    supplierUrl: "https://supplier.example.com/imac-24-m3",
    featured: false,
    active: true,
  },
  {
    title: "Samsung Odyssey G7 32-inch Curved QHD Monitor",
    description:
      "240Hz gaming display with deep contrast and smooth motion for competitive play.",
    category: "Monitor",
    image: "/images/products/samsungmonitor.jpg",
    price: 699,
    compareAtPrice: 799,
    stock: 16,
    supplierName: "Display Source LLC",
    supplierUrl: "https://supplier.example.com/odyssey-g7",
    featured: true,
    active: true,
  },
  {
    title: "LG UltraFine 27-inch 5K IPS Monitor",
    description:
      "Color-accurate 5K panel optimized for design workflows and sharp text clarity.",
    category: "Monitor",
    image: "/images/products/lgmonitor.jpg",
    price: 1299,
    compareAtPrice: 1399,
    stock: 8,
    supplierName: "LG Partner Supplies",
    supplierUrl: "https://supplier.example.com/lg-ultrafine-5k",
    featured: false,
    active: true,
  },
  {
    title: "NVIDIA GeForce RTX 4070 Ti 12GB",
    description:
      "Powerful GPU for high-FPS gaming, 3D rendering, and creator workloads.",
    category: "Components",
    image: "/images/products/gpu.jpg",
    price: 899,
    compareAtPrice: 999,
    stock: 14,
    supplierName: "GPU Wholesale Direct",
    supplierUrl: "https://supplier.example.com/rtx-4070-ti",
    featured: true,
    active: true,
  },
];
