export const products: Product = [
  {
    category: "Gaming",
    title: "Logitech G Pro X Wireless Gaming Headset",
    price: 199.0,
    oldPrice: 229.0,
    image: "/images/products/Logitech-headset.jpg",
    rating: 4,
  },
  {
    category: "Accessories",
    title: "Anker PowerCore 20000mAh Power Bank",
    price: 59.0,
    oldPrice: 69.0,
    image: "/images/products/AnkerPowerBank.jpg",
    rating: 4,
  },
  {
    category: "Accessories",
    title: "KWG Orion E1 Multi-color Gaming Mouse",
    price: 26.0,
    oldPrice: 29.0,
    image: "/images/products/gaming-mouse1.jpg",
    rating: 5,
  },
  {
    category: "Laptop",
    title: "Dell XPS 13 Ultra Thin Performance Laptop",
    price: 1249.99,
    oldPrice: 1399.99,
    image: "/images/products/Delllaptop.jpg",
    rating: 5,
  },
  {
    category: "Laptop",
    title: "HP Spectre x360 Convertible Touch Laptop",
    price: 1149.0,
    oldPrice: 1299.0,
    image: "/images/products/hplaptop.jpg",
    rating: 4,
  },
  {
    category: "Desktop",
    title: "Acer Predator Orion 7000 Gaming Desktop",
    price: 1799.0,
    oldPrice: 1999.0,
    image: "/images/products/acerdesktop.jpg",
    rating: 5,
  },
  {
    category: "Desktop",
    title: "Apple iMac 24-inch M3 Retina 4.5K Display",
    price: 1599.0,
    oldPrice: 1699.0,
    image: "/images/products/appledesktop.jpg",
    rating: 4,
  },
  {
    category: "Monitor",
    title: "Samsung Odyssey G7 32-inch Curved QHD Monitor",
    price: 699.0,
    oldPrice: 799.0,
    image: "/images/products/samsungmonitor.jpg",
    rating: 5,
  },
  {
    category: "Monitor",
    title: "LG UltraFine 27-inch 5K IPS Monitor",
    price: 1299.0,
    oldPrice: 1399.0,
    image: "/images/products/lgmonitor.jpg",
    rating: 4,
  },
  {
    category: "Components",
    title: "NVIDIA GeForce RTX 4070 Ti 12GB GDDR6X",
    price: 899.0,
    oldPrice: 999.0,
    image: "/images/products/gpu.jpg",
    rating: 5,
  },
  {
    category: "Components",
    title: "AMD Ryzen 9 7900X 12-Core Processor",
    price: 469.0,
    oldPrice: 499.0,
    image: "/images/cpu.png",
    rating: 5,
  },
  {
    category: "Gaming",
    title: "Razer BlackWidow V4 Pro Mechanical Keyboard",
    price: 229.0,
    oldPrice: 259.0,
    image: "/images/keyboard.png",
    rating: 5,
  },

  {
    category: "Accessories",
    title: "Logitech MX Master 3S Wireless Mouse",
    price: 99.0,
    oldPrice: 119.0,
    image: "/images/mouse.png",
    rating: 5,
  },
  {
    category: "Peripherals",
    title: "Corsair iCUE H100i RGB PRO XT Liquid Cooler",
    price: 139.0,
    oldPrice: 159.0,
    image: "/images/cooler.png",
    rating: 4,
  },
  {
    category: "Peripherals",
    title: "Elgato Stream Deck MK.2 Controller",
    price: 149.0,
    oldPrice: 169.0,
    image: "/images/streamdeck.png",
    rating: 5,
  },
  {
    category: "Networking",
    title: "TP-Link Archer AX6000 Wi-Fi 6 Router",
    price: 289.0,
    oldPrice: 319.0,
    image: "/images/router.png",
    rating: 5,
  },
  {
    category: "Networking",
    title: "Netgear Nighthawk Mesh Wi-Fi 6 System (3-Pack)",
    price: 499.0,
    oldPrice: 549.0,
    image: "/images/mesh.png",
    rating: 4,
  },
  {
    category: "Software",
    title: "Microsoft Office 2021 Home & Student",
    price: 149.0,
    oldPrice: 169.0,
    image: "/images/office.png",
    rating: 5,
  },
  {
    category: "Software",
    title: "Adobe Photoshop CC Annual Subscription",
    price: 239.0,
    oldPrice: 259.0,
    image: "/images/photoshop.png",
    rating: 5,
  },
  {
    category: "Deals",
    title: "ASUS TUF 27-inch 165Hz Gaming Monitor (Deal of the Week)",
    price: 229.0,
    oldPrice: 299.0,
    image: "/images/dealmonitor.png",
    rating: 5,
  },
];
